### ISSUE TITLE
Got trouble with python

### ISSUE THREAD

**Issue by justintv90** [jalcine/vimrc#6]
Hey

I love your vim setup and i'm using it. It's awesome and i really really love it. I've switched to nvim for a weeks.

I got these errors:

github-issues.vim requires Python support, sorry :c
Coffee auto tag requires Vim to be compiled with Ruby support

I installed neovim python support by "pip install neovim" but it couldn't help it. How can i deal with it? and you didn't use NerdTree, did you? I didn't find the nerdtree in plugins setup

**Comment by woss** [comment]
i had the same issue, i did `pip install --user neovim` and `gem instal neovim` that fixed it. 

Also it would be nice to have all the mappings, there are ton of stuff :)

**Comment by jalcine** [comment]
@justintv90 Hey - did the comments that @woss provide help?

Also @woss which mappings are you referring to? Some things I mapped in a namespaced fashion for lexical ease of use (like with `[vimtest]` and friends). Otherwise, I tend to fall back to the default mappings that plugins provide.

**Comment by woss** [comment]
@jalcine mappings in general. There are so many plugins out there with bunch of mappings, it would be great if there would be a plugin  that generates mappings for other plugins :) 

Although i really like what you have done with this repo I stop using it and started creating my own from scratch. Reason is that i don't like my (N)Vim is an IDE, that supports all kinds of languages builds etc... But for most of my part when i was writing new `init.vim` this repo was my guideline to see how you map stuff, to thank you for that 👍

**Comment by jalcine** [comment]
@woss Something like that would require some kind of metadata exporting from plugins and that'd be tricky since mappings aren't immutable. Nonetheless, I'm glad you found my repo useful as a base!
